### PR TITLE
Actual voltage output and typos

### PR DESCRIPTION
**Pull request by dafvid**
Changed output from read() to be actual voltage instead of raw value

gain should default to 0

fixed typo in alert_start

### CODE REVIEW

**Comment by robert-hh** [comment]
Hello Dafvid. Thank you for your comments. They are very helpful. There were, it seems, some part of the code which I did no test. Some remarks:
- Whether read and read_rev returns the raw value or a voltage, is a matter of style. I prefer raw, but for read() and read_rev() returning the voltage is fine. For alert_read the situation is different, since that is to be called in an interrupt context, where allocating of memory is not possible, depending on the flavour of micropython. Being a float operation, the conversion to voltage allocates memory. 
- In class ADS1015 read() would cause an error, since the shift operator is invalid for floats.
So maybe just providing the raw_to_v() function is sufficient, which based on the actual gain will do the conversion, if needed.

**Comment by robert-hh** [comment]
- I should also add, that alter_read(), being made as an Interrupt service function, should execute as fast as possible. That's another reason to return the raw value in the first step and leave conversion to not time critical sections of the code.
- In read() of  ADS1015, division by 16 could be used instead of shift right.

**Comment by robert-hh** [comment]
Another thought:  when doing a raw_to_v conversion of the ADS1015 class, division is not required, because the range is the same, but just with a reduced resolution.

**Comment by dafvid** [comment]
I'm a bit lost in the git branches atm. Was trying to only add the conversion function. =/
But adding a simple conversion helper function would be great. And maybe add something to the docs regarding what the returned value from read() represents and how to use it. I was a bit confused at first. My use case is I'm using a MCP9700 to measure temperature and it's 10 mV / degrees Celcius. Maybe other implementations are fine with only the binary value.

**Comment by robert-hh** [comment]
I have added the conversion function now based on your input. I did not test it yet, but I'll do. After that, I will publish it. Thank you for you contribution.
I adapted that module for an application measuring conductivity, where like yours the voltage itself was not sufficient anyhow. Unless you use the voltage directly, a conversion has to be applied anyhow, including the tranfer function of your circuitry. So dealing with raw values is OK.

**Comment by robert-hh** [comment]
@dafvid: I tested the raw_to_v function and it worked as expected. It is now added as separate method to the class. The ADS1015 variant copes for the lower granularity of the raw values.
What I did not change is the order of the parameters, even if I understand the reason. I have existing
code that I do not want to change.

**Pull request closed without merging**
